# -*- coding: utf-8 -*-
TITLES = {
 'I':  ('Tablet I','The Coming of Enkidu'),
 'II': ('Tablet II','The Taming, and the Counsel of Uruk'),
 'III':('Tablet III','The Blessing of Ninsun'),
 'IV': ('Tablet IV','The Journey and the Five Dreams'),
 'V':  ('Tablet V','The Cedar Forest'),
 'VI': ('Tablet VI','Ištar and the Bull of Heaven'),
 'VII':('Tablet VII','The Death of Enkidu'),
 'VIII':('Tablet VIII','The Funeral'),
 'IX': ('Tablet IX','The Road of the Sun'),
 'X':  ('Tablet X','At the Edge of the World'),
 'XI': ('Tablet XI','The Flood, the Test, and the Plant'),
 'XII':('Tablet XII','Appendix — Enkidu and the Netherworld'),
}
HEADNOTES = {
 'I': "The prologue praises the man who brought back knowledge from before the Flood, then commands the reader onto the wall of Uruk and into the tablet-box. Gilgameš oppresses his city; the gods answer with a counterweight. Aruru pinches clay, and Enkidu is born among the herds. A hunter's complaint sets Šamhat on the road; six days and seven nights make the wild man human. Two dreams — a meteor and an axe, each loved like a wife — announce the friend.",
 'II': "Šamhat clothes Enkidu; the shepherds' bread and beer complete what her body began. He hears of the king's droit over brides, bars the wedding-house door, and the two collide. From the fragmentary reconciliation grows the expedition: Gilgameš proposes the Cedar Forest, Enkidu and the elders lay out the dossier against Humbaba, and the counsel is set aside with a laugh. The great lacunae in this tablet are supplied in part by the Old Babylonian Pennsylvania and Yale tablets, which are not printed here.",
 'III': "The elders entrust the king to Enkidu. Ninsun, after ritual washing, climbs to the roof and prays to Šamaš — the longest prayer in the poem, indicting the god for the restless heart he fastened on her son, and conscripting Ayya, the thirteen winds, and the watches of the night into his protection. She then adopts Enkidu. The departure follows.",
 'IV': "The march telescopes: fifty leagues a day, a month and a half of road in three days, five times over. At each camp Enkidu builds a house for the dream-god, and Gilgameš buys a dream from the mountain. Each dream is a catastrophe — a falling mountain, a thunderstorm raining death — and each time Enkidu, born in the open land and fluent in omens, reads terror as promise. The formula's repetition is the journey.",
 'V': "The forest is the poem's one landscape painting: resin drizzling like rain, a canopy full of answering birds, monkeys drumming for their lord. Terror falls first on Gilgameš; the roles of encourager and encouraged trade back and forth between the friends — a deliberate chiasmus. Šamaš's thirteen winds pin Humbaba; the ogre pleads, offers vassalage and timber; Enkidu insists on the kill with a fourfold imperative; Humbaba curses them both with the poem's cruelest precision. They fell the forest they came to save, and Enkidu proposes the great door for Nippur — the door that will receive his dying curse.",
 'VI': "Cleaned and crowned after the victory, Gilgameš is proposed to by Ištar. His refusal is a catalogue aria: nine similes of treacherous objects, then six lovers, each loved and ruined. Ištar extorts the Bull of Heaven from Anu; drought and chasms follow it down; the friends kill it by division of labor. Enkidu flings the haunch in the goddess's face — the epic's point of no return.",
 'VII': "Enkidu, sentenced by the gods' council in a dream reported only obliquely, addresses the cedar door as a person and disowns it. He curses the hunter and Šamhat; Šamaš argues from the balance-sheet of what civilization gave him, and the curse is revoked into a blessing — the poem's ethic in miniature. A second dream takes him captive to the house of dust, whose sitting kings and priests he inventories. He sickens by numbered days and dies wishing he had fallen in battle.",
 'VIII': "Gilgameš's lament runs the world in reverse: the paths, mountains, rivers, animals, and tradesmen that made Enkidu are called to weep for him. The dead man is veiled like a bride, circled like an eagle. A statue is commissioned; the treasury is opened, and the grave-goods are enumerated in a long broken ledger, each item 'set out for his friend'; presentation gifts go to each officer of the netherworld — Ereškigal, Namtar, Dumuzi and the rest — to buy the dead man welcome. The tablet ends with offerings shown to the sun.",
 'IX': "Grief becomes itinerary. Gilgameš roves, kills lions in the passes, and reaches Māšu, the twin mountains that gate the sun, guarded by the scorpion-people whose glance is death. Warned that no mortal has done it, he runs the sun's own tunnel — twelve leagues of counted darkness, racing sunrise — and comes out ahead of the sun into the garden where the trees fruit carnelian and lapis: the mineral parody of paradise.",
 'X': "Šiduri the ale-wife bars her door against the lion-clad wanderer; the tablet is built on a triple interrogation — Šiduri, Ur-šanabi, Ūta-napišti — each demanding, in identical verses, why his face is hollowed; each receiving the same lament. He smashes the Stone Ones, poles across the Waters of Death with three hundred expendable poles, and puts his question. Ūta-napišti's answer — the mayfly on the flood, the assembly that set down death and life — is the poem's theological center of gravity.",
 'XI': "Ūta-napišti opens the guarded matter: the Flood, told first-person — the boat cubed like the Apsû, the gods cowering like dogs, Ištar's lament over her drowned people, the dove, the swallow, the raven, and the gods swarming like flies to the first sacrifice. Enlil's blessing exiles the survivor from the human race, and its unrepeatability voids Gilgameš's whole errand. Then the trials: sleep defeated by seven loaves; the washing; the plant of heartbeat won and lost to a snake at a cold pool. The end is the beginning: the wall, the brick, the survey of Uruk.",
 'XII': "An appendix, not a continuation: a line-for-line Akkadian rendering of the second half of the Sumerian poem 'Gilgameš, Enkidu and the Netherworld,' stitched to the epic in defiance of Tablet VII (here Enkidu is alive again, and lost to the underworld by a different door). The ball and mallet fall into the earth; Enkidu breaks every taboo of the silent land; Šamaš opens a chink, and the phantom reports the fates of the dead, ranked by the sons they left — the epic's grim actuarial table, and its argument of last resort for posterity.",
}
APPARATUS = {
 'I': [
  ("I 1 — nagbu","<i>nagbu</i> is both 'deep spring' and 'totality': he who saw the source, and he who saw everything. The translation keeps the water and lets the pun go."),
  ("I 2 — [alkakāti īd]û","The verb is secure; the noun is restored. Older editions read <i>ša kullat īdû</i> here; the eBL text prints <i>[alkakāti]</i>, 'the ways.'"),
  ("I 15 — simmiltu","'Staircase,' not 'threshold' as older translations render: the ascent to Eanna is architectural and processional."),
  ("I 22–23 — šār","One <i>šār</i> = 3,600, a beloved round number; here a unit of urban area. The prologue ends in a surveyor's docket — deliberately."),
  ("I 102 — ilitti qūlti","'Offspring of stillness' — or of the midnight hush, or of Silence personified. Uncertain and untranslatable; the alternative reading takes it as 'offspring of the skull/of Anu.' The strangeness is original."),
  ("I 105 — kīma nissaba","Literally 'like Nissaba,' goddess of grain: his hair grows like a barley-field. So too line 58."),
  ("I 246 — kiṣru ša Āni","A 'lump of Anu' — meteoric iron falling from the sky-god's realm; the same phrase measures Enkidu's strength at I 123 and elsewhere. One noun binds omen to man."),
  ("I 192","Six days and seven nights: the same span as Ūta-napišti's test of sleep (XI 209) and the mourning over Enkidu (X 235). The poem counts in sevens."),
  ("I 1 — the incipit's brackets","The opening line is restored in every surviving manuscript, but the ancient colophons and catch-lines quote <i>ša naqba īmuru</i> entire; the English stands unbracketed on that authority."),
  ("I 64 — pukku","The <i>pukku</i> ('ball-game') is a genuine crux — ball, hoop, or drum. Whatever the object was, Tablet XII hangs from its loss."),
  ("I 179 · 187 — ūru","<i>ūrki pitê</i> is 'open your vulva' — the plain anatomical noun. An earlier state of this translation had 'lap,' the euphemism that belongs to <i>sūnu</i> (kept where the poem itself is discreet, VII 128–129). The Akkadian is direct here; the English now is too."),
  ("I — collation","All 300 lines collated word-by-word against the eBL reconstruction, August 2026. Besides <i>ūru</i>, the pass removed two amplifications that had crept into refrains ('grazing' at 125 = 152; a bent posture in the murmuring-refrain of the dreams), restored the dative of <i>illikannâši</i> 'came to us' (121 = 148), standardized <i>lullû</i> 'first-made man' at 183 = 190, and marked the uncertainty of <i>š[arru?]</i> 68. Register verdict: faithful — <i>kuzbu</i> sensual, not obscene; the Šamhat episode direct without coarsening."),
 ],
 'II': [
  ("II 36 — kīma ili","Šamhat leads Enkidu 'like a god' — the simile of procession: as a cult statue is led. He enters culture as an image enters a temple."),
  ("II 44–48","Bread and beer are the diagnostic human foods; the wild man 'squints and stares.' The OB Pennsylvania tablet preserves the scene whole; the SB text is broken here."),
  ("II 110 — pūhu","A 'counterpart' or substitute is set up for Gilgameš 'like a god' at the wedding — the rite (and the king's claim on the bride) that Enkidu blocks."),
  ("II 234–235","'As for man — his days are numbered; whatever he ever does is only wind': Gilgameš's carpe-diem heroism before the fact of death; the whole later poem is this couplet refuted."),
  ("II 221–222","Humbaba's dossier — voice the Flood, mouth fire, breath death — is repeated verbatim four times in this tablet: fixed liturgy of dissuasion, spoken by Enkidu, the elders, and the counsellors in turn."),
  ("II 220 = 277 — lā sākip","'Unsleeping' takes <i>sakāpu</i> B 'to lie down.' The homonym <i>sakāpu</i> A 'to thrust away' would give 'irresistible' — both suit a watchman-ogre; the translation keeps the insomniac reading."),
  ("II — collation","187 lines collated. Corrections from the pass: '[they kis]sed(?)' for the uncertain <i>ittašqū</i> (a softened 'embraced' abandoned), <i>mindē-ma</i> 'perhaps' at 42, dual 'feet' at 111, an unwarranted 'and uncut' dropped at 176, and the seared heart of 189 (<i>ṣarāpu</i>, 'to burn') recovered from a mistaken 'knotted.' Six broken lines that keep one legible word each now carry that word."),
 ],
 'III': [
  ("III 46 — tēmissu","Ninsun's prayer opens as an indictment: Šamaš 'fastened' (lit. imposed) a restless heart on her son. The mother blames the god for the hero's nature."),
  ("III 87–93","Thirteen winds, individually named. The list recurs at V 159–163 when they are actually deployed; several names (ziqziqqu, šaparziqqu, imhullu) are demon-winds otherwise at home in incantations."),
  ("III 96 — parûka hanṭūtu","'Your swift mules': the sun travels by mule-team, storm-beasts. Cf. the chariot-mules Ištar offers at VI 12."),
  ("III 121–128","The adoption of Enkidu among the oblates: legal formulae (the emblem on the neck, the foundling clause) transposed into epic. Ninsun converts friendship into kinship before the law."),
  ("III 119 — ukabbit qutrinnam","<i>kubbutu</i> of an incense-offering is to make it heavy — generous — not to damp it. Ninsun heaps the censer high; an earlier rendering inverted the gesture."),
  ("III — collation","209 lines collated. The pass restored the second-person elements Ninsun's indictment needs ('your torch' 80, 'for him' 88, 'the great one' 99 = 86), gave <i>šahāṭu</i> its urgency ('dashed to the stair,' 43), and standardized the elders' send-off at 10 = 225: 'bring him home to the wives' — <i>hīrāti</i>, and no arms in the Akkadian."),
 ],
 'IV': [
  ("IV 1–4","Fifty leagues a day — roughly 540 km — 'a march of a month and a half in three days.' Epic arithmetic, repeated five times as a formula; the journey exists only as repetition."),
  ("IV 10 — bīt zaqīqi","A 'house of the dream-god' (Zaqīqu, the wind-phantom): a ritual incubation hut built nightly. The circle and the door of storm-wood are apotropaic architecture."),
  ("IV 26 — mitluka ileʾʾi","Enkidu 'knows how to counsel' precisely because he was born in the open land: wilderness is credentialed as hermeneutics."),
  ("IV 101–106","The third dream is the best preserved: sky screaming, day gone still, raining death, then ash. Enkidu reads every apocalypse as a good omen. The poem lets the audience hear what he will not."),
  ("IV 23 — sapannu","<i>sapannu</i> is level ground — the flank of the mountain, not a ravine; the line is heavily restored either way."),
  ("IV — collation","175 lines collated. The five-fold journey and dream apparatus is internally exact; the pass trimmed one stray gloss from the first dream-house (10) and restored the emphatic <i>u šū</i> 'and he himself' at 91 and 174 to match its parallels."),
 ],
 'V': [
  ("V 15–26 — the forest symphony","Resin as rain, gullies as its drainage, and a full orchestra: bird, cricket, wood-pigeon, turtle-dove, stork, francolin, mother apes, infant apes — 'like a band of singers and drums' (<i>nārī u tigî</i>) before their king. The one place the poem stops to listen."),
  ("V 42 — kī apillî","Obscure: 'like an <i>apillû</i>' — perhaps a cult-performer or berserker. The context demands whipped-up battle-frenzy; the translation paraphrases."),
  ("V 132–135","Enkidu's pep-talk is a founder's metaphor: the copper is already in the channel — too late to stop the pour. Then, astonishingly: 'to send the Flood is to crack the whip' — deluge as routine work."),
  ("V 156 — Sirara u Labnānu","Their whirling splits the twin ranges: Sirion (Hermon) and Lebanon. A Levantine geography remembered precisely in Babylonia."),
  ("V 300–306","Having killed the warden, they strip the forest he warded. Enkidu himself names the crime: 'we have turned the forest into a wasteland — what shall we answer Enlil?' The poem is not naive about this."),
  ("V 307–310 — the seven sons","The 'sons' of Humbaba — Cricket, Screamer, and the rest — are best read as his seven auras or terror-radiances, here personified and slaughtered. Text and count both uncertain."),
  ("V 116 — lillū … nuʾû","Humbaba's first insult: 'Let fools take counsel, Gilgameš, with louts!' — the fool and the witless man are Gilgameš's advisers, that is, Enkidu. Some construe <i>nuʾû amēlu</i> instead as a vocative aimed at Gilgameš himself."),
  ("V 198 = 199 = 267 = 268 — ṭēnšu hulliq","The kill-formula is three imperatives — 'finish him! kill him! grind up his mind!' A fourth ('destroy him') had crept into all four instances and is removed."),
  ("V — collation","274 lines collated. Corrections: 'singers and drums' for <i>nārī u tigî</i> (25), the temporal <i>ištu ullânum-ma</i> 'then and there' (55, as at 96), <i>mindē-ma</i> 'perhaps' (69), and several conjectural fills returned to their brackets (92, 122, 260, 278). Humbaba's threats and dying curses stand at full force."),
 ],
 'VI': [
  ("VI 12 — kūdanī ūmī","'Great mules that are storms' — the goddess's chariot-team. The same word 'storm' (<i>ūmu</i>) is the Flood's own; her dowry is catastrophe in harness."),
  ("VI 33–41","Nine similes of failed objects: hearth, back-door, palace, elephant, pitch, waterskin, limestone, battering-ram, shoe. Each a thing that ruins the one who trusts it. Ancient scholars already read them as a set-piece."),
  ("VI 46–79 — the lovers","Six case-studies: Dumuzi, roller-bird, lion, horse, shepherd, Išullānu — a descending scale from god to gardener, each 'loved' into ruin. The horse's sentence includes churned water; the shepherd becomes a wolf hunted by his own dogs."),
  ("VI 99–100","Ištar's threat to raise the dead to eat the living recurs verbatim in her descent to the netherworld — a standing formula of divine blackmail."),
  ("VI 104–111","The price of the Bull: seven years of stored chaff and hay against the drought it will bring. Anu's condition is famine-insurance; Ištar has already stockpiled."),
  ("VI 162–165","The horns: thirty minas of lapis inlay, two of rim-work, six measures of oil poured to Lugalbanda. The trophy is instantly liturgical furniture."),
  ("VI 40 — māt nukurti","'The wall of the enemy land': so the Akkadian, plainly. The logic of the treacherous-objects catalogue (33–41) tempts an emendation — the ram that betrays its own besieged masters — and an earlier state of this translation yielded to it; the text as transmitted is restored here."),
  ("VI 69 — hurdatu","Ištar's word for what Išullānu should touch is <i>hurdatu</i> — rarer and blunter than <i>ūru</i>, and certainly no 'sweet place.' Now 'vulva': the goddess is not coy, and the translation must not be."),
  ("VI — collation","183 lines collated. The catalogue of lovers now keeps its frame-echo — <i>hāmeru</i> 'bridegroom' at 42 and 46 alike — and closes on <i>târu</i> as it must: 'and like them you will turn me' (79), the transformation-verb of the whole aria."),
 ],
 'VII': [
  ("VII 37–64 — the door speech","Enkidu addresses the cedar door as a person ('awareness is in you that is not there'), rehearses its dimensions from V 316–317, and disinherits it. To curse the door is to curse his own entry into culture."),
  ("VII 102–147 — curse and blessing","The curse of Šamhat itemizes a prostitute's street-life clause by clause; Šamaš's rebuttal is an invoice of benefits (bread, ale, garment, friend); the revocation converts each curse into its mirror blessing. Assyriologists read here the poem's whole theory of civilization."),
  ("VII 184–190 — the house of dust","The description of the netherworld — feathered dead in darkness, dust for hunger, clay for bread — recurs nearly verbatim in Ištar's Descent and Nergal and Ereškigal: shared funerary boilerplate, which is itself the horror."),
  ("VII 196–197","The dead kings serve the gods roast and cool water: royal privilege inverted into eternal waiting-service."),
  ("VII 266–267","'One who fell in battle made his name; I fall to no battle, and make no name': the shame of dying in bed. Tablet XII 148–149 will grant the battle-dead their cradled head — the two passages answer each other."),
  ("VII 94 — habbilu","The hunter is <i>habbilu</i> — <i>habālu</i> 'to snare' shadowed by its homonym 'to wrong.' 'The snaring man' keeps the trap and lets the crime sound underneath; the pun is likely the poet's."),
  ("VII 138 · 160 — kâša, kâši","The emphatic independent pronouns in Šamaš's argument and the reversed curse are second person — 'you, yes you' — not a third party; both corrected in collation."),
  ("VII — collation","219 lines collated. The dead man of 76 (<i>[mīt]u</i>) is restored to his proverb; 'my mouth' (152) recovers the possessive the blessing turns on; <i>zêru</i> 263 is hatred, not cursing; the unbracketed 'made his name' of 266 returns to its brackets. The curse of Šamhat and its reversal run at full force, with <i>sūnu</i> correctly discreet."),
 ],
 'VIII': [
  ("VIII 1–41 — libkīka","The lament is an anaphora on 'may they mourn you' (<i>libkīka</i>), summoning in order: paths, elders, crowd, mountains, meadows, trees, sixteen species of animal, two rivers, then the tradesmen — ploughman, herdsman, shepherd-boy, brewer, harlot. Enkidu's biography retold as a mourners' census."),
  ("VIII 50 — kūdannu ṭardu","'Swift mule' (lit. 'driven mule'), wild ass, panther: the triple apostrophe returns as the fixed epithet of the dead friend through Tablet X."),
  ("VIII 59 — kīma kallati","He veils the corpse 'like a bride': the marriage the dreams promised (loved 'like a wife,' I 254) is consummated as funeral."),
  ("VIII 135–183 — presentation gifts","Each officer of the netherworld receives a named gift shown to Šamaš — Ištar, Bēlet-ilī, Ereškigal, Dumuzi, Namtar, Hušbiša, Qāssa-ṭābat the sweeper, Ninšuluhha the housekeeper, Bibbu the slaughterer, Dumuzi-abzu — with the refrain 'may she welcome my friend and walk at his side.' Diplomacy conducted downward."),
  ("VIII 212 — sikra ša nāri","'The damming of the river': the burial of kings under a diverted riverbed — as in the Sumerian Death of Gilgameš, where the Euphrates itself is turned to roof the tomb."),
  ("VIII 39 — eli ṣērīšun","The sisters loosen their hair 'over their own backs' (<i>-šun</i>) — the mourning gesture is theirs, not draped over the dead man; corrected from an 'over you' carried in from the brothers' line."),
  ("VIII — collation","206 lines collated. The presentation-refrain tracks each netherworld officer's gender in the Akkadian verb; 166 (<i>hadī-ma</i>, of Ereškigal's sweeper) is masculine and now reads 'may he.' Several ledger brackets re-set to the clay (132, 139, 185, 199). The grave-goods keep their plain concreteness."),
 ],
 'IX': [
  ("IX 3","<i>amât-ma ul kī Enkīdū-mâ</i>: 'I shall die — and shall I not be as Enkidu is?' The grammar is a question that answers itself; the whole quest is this line."),
  ("IX 38–45 — Māšu","'Twins' by name: the double peak through which the sun passes nightly, its tops against heaven, its breasts reaching Arallû. The scorpion-guards' glance is death, yet they talk shop courteously."),
  ("IX 139–170 — the tunnel","Twelve leagues of counted darkness, each league a couplet: 'the darkness is dense, and there is no light; it does not let him see behind him.' At the ninth the north wind licks his face; at the twelfth he exits 'ahead of the sun' — he has outrun sunrise through the mountain."),
  ("IX 173–190 — the jeweled garden","Carnelian fruit, lapis foliage, thorns of crystal, carob of abašmu-stone: a garden where everything living is replaced by its precious simulacrum. He reaches paradise and it is a lapidary's shop — the first taste of the immortality on offer."),
  ("IX 13 — itbe","<i>itbe</i> is 'he arose' — Gilgameš starting up from his dream, not lying down to it; corrected in collation."),
  ("IX — collation","137 lines collated. Two words for 'lion' (<i>nēšu</i> 9, <i>labbū</i> 18) share one English; the '(the twins)' of 39 makes explicit what the mountain's name says in Akkadian (see on 38–45); an added 'everywhere' at 171 is removed. The tunnel-refrain is word-exact."),
 ],
 'X': [
  ("X 40–45 — the interrogation formula","'Why are your cheeks hollow...' — six verses, asked verbatim by Šiduri, Ur-šanabi, and Ūta-napišti, answered each time by the same lament with its negations intact ('why should my cheeks not be hollow...'). Grief has become liturgy; the repetition is the meaning."),
  ("X 72–91 — Šiduri's directions","In this late version the ale-wife gives sailing directions. In the Old Babylonian version she gives instead the carpe-diem speech (bread, clean clothes, the child, the wife) — the most famous lines the Standard Babylonian edition deleted; they are not in this text."),
  ("X 102–106 — šūt abnī","'The Stone Ones': crew, ballast, or stone crewmen immune to the lethal water — deliberately mysterious. Gilgameš destroys, in rage, the only safe means of his own crossing: the poem's clearest self-portrait of him."),
  ("X 172–183","Three hundred poles, each used once and dropped: the Waters of Death permit contact with nothing. The last stretch is sailed with his own stripped garment for a sail — he arrives naked of everything but purpose."),
  ("X 301 — qan appāri","Mankind's name is 'reed snapped in the canebrake.' The Euphrates valley's own image: brittle, plural, renewable — but not the individual reed."),
  ("X 313–315 — kulīlu","The mayfly drifting on the flood, face to the sun, 'and then, all at once, nothing was there at all.' The shortest-lived creature in the river answers the longest question in the poem."),
  ("X 319–322","The Anunnaki fix destinies with Mammītum: 'they set down death, and they set down life — and of death they did not disclose the day.' Symmetry as consolation; concealment as mercy."),
  ("X 267 — mārat Āni","<i>nissatu mārat Āni</i>: grief is 'the daughter of Anu' — sorrow given a genealogy; the feminine construct rules out taking the phrase of Gilgameš."),
  ("X 270–271 — palace and throne","'Has anyone ever built the fool a palace?' (<i>ēkalla</i>) — and then the throne of 271. An earlier rendering collapsed the pair into two thrones."),
  ("X — collation","325 lines collated. The triple interrogation and lament repeat verbatim by design and survive collation intact (one strayed '[not]' at 225 restandardized). The mayfly discourse keeps the <i>haṣpu/hāṣip</i> wordplay; conjectural fills at 174 and 275 returned to their brackets."),
 ],
 'XI': [
  ("XI 21–22 — kikkiš kikkiš","Ea evades his oath by addressing the reed fence, not the man behind it: divine legalism, and the poem knows it — Ea's own defense at XI 196–197 ('I let him see a dream') repeats the trick."),
  ("XI 31 — kīma apsî","The boat is cubed 'like the Apsû,' the freshwater deep: a floating cosmological model, ten rods to a side, seven storeys, nine bays."),
  ("XI 46–47 — kukkī / kibāti","The weather-sign is a pun: 'bread-cakes' (<i>kukku</i>) shadows 'darkness' (<i>kukkû</i>), 'wheat' (<i>kibtu</i>) shadows 'heaviness.' Ea promises rain of bread that is also rain of dark."),
  ("XI 116 — kīma kalbī","The gods 'curled up like dogs' outside the world they wrecked — the Flood narrative's harshest verse, and its theology in one simile."),
  ("XI 141 — fourteen regions","Read <i>14 nagbātu(?)</i> with eBL: fourteen coastal regions emerge, not twelve as in older editions."),
  ("XI 142 — Nimuš","The landing mountain, formerly read 'Niṣir'; the eBL text prints Nimuš (likely Pir Omar Gudrun in Iraqi Kurdistan)."),
  ("XI 148–156 — the three birds","Dove, swallow, raven — each verb-set distinct; the raven 'eats, wades, bobs its tail.' Ornithological exactness as the first sign of a world again habitable."),
  ("XI 163 — kīma zumbē","The starving gods gather 'like flies over the man of the sacrifice' — then Ištar lifts her fly-shaped beads as the token of memory. The simile and the jewel are the same word: the poet is watching his own metaphor."),
  ("XI 203–206 — the blessing as exile","'Let Ūta-napišti live far away, at the mouth of the rivers': immortality is granted as removal from mankind. Unrepeatable by its own terms — which is the answer Gilgameš came for."),
  ("XI 225–230 — the seven loaves","The stages of stale bread as a calendar of failed wakefulness: the man who would defeat death cannot defeat a week of sleep."),
  ("XI 305–307 — the snake","<i>nēšu ša qaqqari</i>, 'lion of the ground,' takes the plant and sheds its slough: rejuvenation transfers to the animal kingdom on a technicality. The theft is a bath-interval: he lost eternity to hygiene."),
  ("XI 323–328 — the ring","The closing lines repeat the prologue's wall-circuit verbatim, now spoken by Gilgameš to Ur-šanabi. What he brings home is the point of view of the opening — which the prologue told us he wrote."),
  ("XI 127 · 132–133a","Two fully preserved Flood lines were missing from the translation and are supplied in collation: 'their lips scabbed over, seized with fever-heat'; 'the sea, that had thrashed like a woman in labor, grew calm.'"),
  ("XI 193 = 195 — šagāšu","Famine and Erra 'slaughter' the land — <i>šagāšu</i> is massacre, not culling; Ea's counterfactuals are restored to their full violence."),
  ("XI 220 — raggat … iraggigki","'Man is a cheat; he will try to cheat you' keeps the Akkadian's figura etymologica (<i>raggu/ragāgu</i>); the broader sense is 'wicked … wrong you.'"),
  ("XI — collation","329 lines collated. The Flood narrative is word-exact through its nested speeches; 'for the workmen' (71) had no Akkadian and is removed; bread-mould and clean garment share <i>šīpu</i> (228, 261, 270), an echo the English splits between 'mould' and 'stain.'"),
 ],
 'XII': [
  ("XII 1–5 — pukku and mikkû","Ball and mallet (or drum and drumstick — the pair is disputed): playthings of the king's exhausting game (cf. I 64), fallen into the underworld through the earth. The appendix's premise ignores Tablets VII–VIII entirely: Enkidu lives."),
  ("XII 11–30 — the taboos","The rules of the silent land are inversions of mourning: no clean garment, no sweet oil, no sandals, no kiss, no blow. To pass unremarked among the dead one must already behave as one. Enkidu breaks every rule in sequence — the narrative simply replays the list in the indicative."),
  ("XII 28–30 — the mother of Ninazu","The uncovered goddess who lies (Ereškigal in her mourning aspect): her bare shoulders and breast 'like an unguent-jar' are the fixed image of the netherworld's grief."),
  ("XII 96–99","The phantom's first report is the body's fate — the penis the worm devours, the crotch full of dust — before any accounting of shades. Gilgameš's response is to throw himself in the dust he has just heard described."),
  ("XII 102–153 — the census of the dead","Welfare in the afterlife is indexed to surviving sons: one (a peg in the wall, weeping), two (bread on bricks), up to seven ('a junior among the gods'); then the special cases — the battle-dead cradled by his parents, the unburied who finds no rest, the untended shade eating pot-scrapings from the street. The epic's final argument: posterity, not escape, is what a mortal can hold."),
  ("XII 98 — ūru, by referent","The same noun rendered 'vulva' of Šamhat (I 179) is here of a man's body and is rendered 'crotch.' The register rule cuts by referent, not by lexeme; the frankness is identical."),
  ("XII — collation","139 lines collated. The taboo-list and the fates of the dead are clause-exact with correct person-switching; beneath the standardized breast-refrain the Akkadian itself varies (<i>šappati/šikkati</i>, <i>lā/ul</i>, 30 vs 50)."),
 ],
}
